#!/usr/bin/sh
target=$1
script_dir="$(dirname "$(readlink -f "$0")")"
js_file="$script_dir/../cloudapi/server.js"
filetype="texts"
fileext=$(expr "$target" : '.*\.\(.*\)$')
imagetypes=("png" "jpg" "jpeg" "webm")
port_value=$(jq -r '.PORT' "$script_dir/../cloudapi/config/serverconfig.json")

if [ -z $target ]; then
    echo "Please specify a target file to delete"
    exit 1
fi

for element in "${imagetypes[@]}"; do 

	if [[ "$element" == "$fileext" ]]; then
		filetype="images"
	fi

done

curl -X DELETE http://localhost:$port_value/$filetype?file=$target
