#!/usr/bin/sh
target=$1
script_dir="$(dirname "$(readlink -f "$0")")"
js_file="$script_dir/../cloudapi/server.js"
port_var="PORT"
port_value=$(grep -oP "(?<=const $port_var = )\d+" "$js_file")

curl -X DELETE http://localhost:$port_value/texts?file=$target
