#!/usr/bin/sh
filename=$1
filetype=$2
downloaddir=$3
script_dir="$(dirname "$(readlink -f "$0")")"
js_file="$script_dir/../cloudapi/server.js"
port_var="PORT"
port_value=$(grep -oP "(?<=const $port_var = )\d+" "$js_file")

if [ -z $filename ]; then
	echo "Please specify a file to upload"
	exit 1
fi	


if [[ $2 == "image" ]]; then
	filetype="images"
elif [[ $2 == "text" ]]; then
	filetype="texts"
else
	echo "Please specify "text" or "image" file type as second argument"
	exit 1
fi

curl -X GET http://localhost:$port_value/$filetype?file=$filename -o $downloaddir/$filename