#!/usr/bin/sh
filename=$1
downloaddir=$3
filetype="texts"
fileext=$(expr "$filename" : '.*\.\(.*\)$')
imagetypes=("png" "jpg" "jpeg" "webm")
script_dir="$(dirname "$(readlink -f "$0")")"
js_file="$script_dir/../cloudapi/server.js"
port_var="PORT"
port_value=$(grep -oP "(?<=const $port_var = )\d+" "$js_file")

if [ -z $filename ]; then
	echo "Please specify a file to upload"
	exit 1
fi

if [ -z $downloaddir ]; then
	downloaddir="./"
fi

for element in "${imagetypes[@]}"; do 

	if [[ "$element" == "$fileext" ]]; then
		filetype="images"
	fi

done

curl -X GET http://localhost:$port_value/$filetype?file=$filename -o $downloaddir/$filename