#!/usr/bin/sh
script_dir="$(dirname "$(readlink -f "$0")")"
js_file="$script_dir/../cloudapi/server.js"
port_var="PORT"
port_value=$(grep -oP "(?<=const $port_var = )\d+" "$js_file")

curl -X GET http://localhost:$port_value | jq
