#!/usr/bin/sh
script_dir="$(dirname "$(readlink -f "$0")")"
js_file="$script_dir/../cloudapi/server.js"
port_value=$(jq -r '.PORT' "$script_dir/../cloudapi/config/serverconfig.json")

curl -X GET http://localhost:$port_value | jq
