#! /usr/bin/sh
filepath=$1
filename=$(basename $filepath)
filetype="texts"
fileext=$(expr "$filename" : '.*\.\(.*\)$')
imagetypes=("png" "jpg" "jpeg" "webm")
script_dir="$(dirname "$(readlink -f "$0")")"
js_file="$script_dir/../cloudapi/server.js"
port_value=$(jq -r '.PORT' "$script_dir/../cloudapi/config/serverconfig.json")

if [ -z $filepath ]; then
	echo "Please specify a file to upload"
	exit 1
fi	

if [ -z $downloaddir ]; then
	downloaddir="./"
fi

for element in "${imagetypes[@]}"; do 

	if [[ "$element" == "$fileext" ]]; then
		filetype="images"
	fi

done

filename=$(basename "$filepath")
curl -X POST -F "file=@$filepath" "http://localhost:$port_value/$filetype?file=$filename"
